### ISSUE TITLE
The app says it's paired and connected but no data show

### ISSUE THREAD

**Issue by TomasHubelbauer** [COM8/UWP-Onewheel#5]
Hey, thanks for this amazing app! I am trying to put together a Web Bluetooth based one and your app has been really used in trying to crack the handshake process. However, I still couldn't get it to work (I never hear back from the board basically, even though as far as I can tell I am initiating the handshake correctly). I am trying with your app, but what I see is that when I pair with the board, the app says it's paired, but no values ever update etc.

You may already know about this, I try to follow the handshake reverse engineering thread and I know it was tricky to make it work.

In any case, I am providing extra info and offering to connect in order to debug if you need support / verification with other boards. This particular board I am testing with is at HW revision 4208 and FW revision 4134 (Gemini). I am in a position to try with more boards, but not sure yet if necessarily with different FW revisions.

If that can help reverse engineer the unlock handshake for more boards, I'll be happy to collaborate and provide any logs etc.

**Comment by COM8** [comment]
Thanks!

It works for my OW+ (HW: 3206 and FW: 4034).
The problem I can spot is:
The [unlock mechanism is waiting](https://github.com/COM8/UWP-Onewheel/blob/master/OnewheelBluetooth/Classes/OnewheelUnlockHelper.cs#L82) for firmware revision [4034 (0x0fc2)](https://github.com/COM8/UWP-Onewheel/blob/master/OnewheelBluetooth/Classes/OnewheelUnlockHelper.cs#L17) to arrive from the board.
Since you probably own a OW+XR this should be changed to your firmware revision (4134 (0x1026)).

Let me know if it works for you. If not, please post your logs.

**Comment by COM8** [comment]
If you need help with characteristics you can have a look over at: https://github.com/COM8/Onewheel-Doc
Over there **I started** documenting all the OW characteristics and stuff I discovered while writing the app.

**Comment by TomasHubelbauer** [comment]
Thanks! That was it, I have changed it and now I am able to connect with it.

**Comment by COM8** [comment]
I will keep it open until I've got a fix for it.

**Comment by TomasHubelbauer** [comment]
FYI I have ported your unlock code to Web Bluetooth, you may find this to be of interest:

https://github.com/TomasHubelbauer/onewheel-web-bluetooth
